In [ ]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [ ]:
data = pd.read_csv('data/raw/US_flights_2023.csv')

In [13]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 6743404 entries, 0 to 6743403
Data columns (total 24 columns):
 #   Column              Dtype
---  ------              -----
 0   FlightDate          str
 1   Day_Of_Week         int64
 2   Airline             str
 3   Tail_Number         str
 4   Dep_Airport         str
 5   Dep_CityName        str
 6   DepTime_label       str
 7   Dep_Delay           int64
 8   Dep_Delay_Tag       int64
 9   Dep_Delay_Type      str
 10  Arr_Airport         str
 11  Arr_CityName        str
 12  Arr_Delay           int64
 13  Arr_Delay_Type      str
 14  Flight_Duration     int64
 15  Distance_type       str
 16  Delay_Carrier       int64
 17  Delay_Weather       int64
 18  Delay_NAS           int64
 19  Delay_Security      int64
 20  Delay_LastAircraft  int64
 21  Manufacturer        str
 22  Model               str
 23  Aicraft_age         int64
dtypes: int64(11), str(13)
memory usage: 1.2 GB

In [14]:
data.describe()

,Day_Of_Week,Dep_Delay,Dep_Delay_Tag,Arr_Delay,Flight_Duration,Delay_Carrier,Delay_Weather,Delay_NAS,Delay_Security,Delay_LastAircraft,Aicraft_age
count,6.743404e+06,6.743404e+06,6.743404e+06,6.743404e+06,6.743404e+06,6.743404e+06,6.743404e+06,6.743404e+06,6.743404e+06,6.743404e+06,6.743404e+06
mean,3.982793e+00,1.220099e+01,3.790013e-01,6.627152e+00,1.402978e+02,5.169804e+00,7.428505e-01,2.566957e+00,3.064876e-02,5.681108e+00,1.348063e+01
std,2.001762e+00,5.507936e+01,4.851385e-01,5.707892e+01,7.287216e+01,3.645732e+01,1.435393e+01,1.500484e+01,1.628923e+00,3.044647e+01,7.891495e+00
min,1.000000e+00,-9.900000e+01,0.000000e+00,-1.190000e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
25%,2.000000e+00,-5.000000e+00,0.000000e+00,-1.500000e+01,8.700000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,7.000000e+00
50%,4.000000e+00,-2.000000e+00,0.000000e+00,-6.000000e+00,1.240000e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.200000e+01
75%,6.000000e+00,9.000000e+00,1.000000e+00,9.000000e+00,1.710000e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+01
max,7.000000e+00,4.413000e+03,1.000000e+00,4.405000e+03,7.950000e+02,3.957000e+03,1.860000e+03,1.708000e+03,1.460000e+03,3.581000e+03,5.700000e+01

In [20]:
data.describe(include="object")

/tmp/ipykernel_51551/460854327.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  data.describe(include="object")

,FlightDate,Airline,Tail_Number,Dep_Airport,Dep_CityName,DepTime_label,Dep_Delay_Type,Arr_Airport,Arr_CityName,Arr_Delay_Type,Distance_type,Manufacturer,Model
count,6743404,6743404,6743404,6743404,6743404,6743404,6743404,6743404,6743404,6743404,6743404,6743404,6743404
unique,365,15,5963,350,344,4,3,350,344,3,3,5,21
top,2023-11-26,Southwest Airlines Co.,N488HA,ATL,"Chicago, IL",Morning,Low <5min,ATL,"Chicago, IL",Low <5min,Short Haul >1500Mi,BOEING,737 NG
freq,20511,1421238,3327,332935,338766,2611567,5409737,332941,338319,5403727,5872159,3122320,2703494

In [17]:
data.isnull().sum()

FlightDate            0
Day_Of_Week           0
Airline               0
Tail_Number           0
Dep_Airport           0
Dep_CityName          0
DepTime_label         0
Dep_Delay             0
Dep_Delay_Tag         0
Dep_Delay_Type        0
Arr_Airport           0
Arr_CityName          0
Arr_Delay             0
Arr_Delay_Type        0
Flight_Duration       0
Distance_type         0
Delay_Carrier         0
Delay_Weather         0
Delay_NAS             0
Delay_Security        0
Delay_LastAircraft    0
Manufacturer          0
Model                 0
Aicraft_age           0
dtype: int64

In [26]:
data.head(10)

,FlightDate,Day_Of_Week,Airline,Tail_Number,Dep_Airport,Dep_CityName,DepTime_label,Dep_Delay,Dep_Delay_Tag,Dep_Delay_Type,...,Flight_Duration,Distance_type,Delay_Carrier,Delay_Weather,Delay_NAS,Delay_Security,Delay_LastAircraft,Manufacturer,Model,Aicraft_age
0,2023-01-02,1,Endeavor Air,N605LR,BDL,"Hartford, CT",Morning,-3,0,Low <5min,...,56,Short Haul >1500Mi,0,0,0,0,0,CANADAIR REGIONAL JET,CRJ,16
1,2023-01-03,2,Endeavor Air,N605LR,BDL,"Hartford, CT",Morning,-5,0,Low <5min,...,62,Short Haul >1500Mi,0,0,0,0,0,CANADAIR REGIONAL JET,CRJ,16
2,2023-01-04,3,Endeavor Air,N331PQ,BDL,"Hartford, CT",Morning,-5,0,Low <5min,...,49,Short Haul >1500Mi,0,0,0,0,0,CANADAIR REGIONAL JET,CRJ,10
3,2023-01-05,4,Endeavor Air,N906XJ,BDL,"Hartford, CT",Morning,-6,0,Low <5min,...,54,Short Haul >1500Mi,0,0,0,0,0,CANADAIR REGIONAL JET,CRJ,17
4,2023-01-06,5,Endeavor Air,N337PQ,BDL,"Hartford, CT",Morning,-1,0,Low <5min,...,50,Short Haul >1500Mi,0,0,0,0,0,CANADAIR REGIONAL JET,CRJ,10
5,2023-01-07,6,Endeavor Air,N336PQ,BDL,"Hartford, CT",Morning,-10,0,Low <5min,...,62,Short Haul >1500Mi,0,0,0,0,0,CANADAIR REGIONAL JET,CRJ,10
6,2023-01-14,6,Endeavor Air,N311PQ,LGA,"New York, NY",Afternoon,-8,0,Low <5min,...,117,Short Haul >1500Mi,0,0,0,0,0,CANADAIR REGIONAL JET,CRJ,10
7,2023-01-21,6,Endeavor Air,N917XJ,LGA,"New York, NY",Afternoon,-10,0,Low <5min,...,125,Short Haul >1500Mi,0,0,0,0,0,CANADAIR REGIONAL JET,CRJ,16
8,2023-01-28,6,Endeavor Air,N336PQ,LGA,"New York, NY",Afternoon,-5,0,Low <5min,...,130,Short Haul >1500Mi,0,0,0,0,0,CANADAIR REGIONAL JET,CRJ,10
9,2023-01-09,1,Endeavor Air,N491PX,LGA,"New York, NY",Evening,-7,0,Low <5min,...,63,Short Haul >1500Mi,0,0,0,0,0,CANADAIR REGIONAL JET,CRJ,4

In [27]:
data.tail(10)

,FlightDate,Day_Of_Week,Airline,Tail_Number,Dep_Airport,Dep_CityName,DepTime_label,Dep_Delay,Dep_Delay_Tag,Dep_Delay_Type,...,Flight_Duration,Distance_type,Delay_Carrier,Delay_Weather,Delay_NAS,Delay_Security,Delay_LastAircraft,Manufacturer,Model,Aicraft_age
6743394,2023-12-31,7,JetBlue Airways,N937JB,BOS,"Boston, MA",Afternoon,60,1,Medium >15min,...,80,Short Haul >1500Mi,43,0,0,0,0,AIRBUS,A321,10
6743395,2023-12-31,7,JetBlue Airways,N945JT,SFO,"San Francisco, CA",Morning,-8,0,Low <5min,...,326,Medium Haul <3000Mi,0,0,0,0,0,AIRBUS,A321,10
6743396,2023-12-31,7,JetBlue Airways,N558JB,ORH,"Worcester, MA",Afternoon,-4,0,Low <5min,...,169,Short Haul >1500Mi,0,0,0,0,0,AIRBUS,A320,24
6743397,2023-12-31,7,JetBlue Airways,N284JB,BOS,"Boston, MA",Afternoon,-5,0,Low <5min,...,85,Short Haul >1500Mi,0,0,0,0,0,EMBRAER,190/195,16
6743398,2023-12-31,7,JetBlue Airways,N661JB,JFK,"New York, NY",Morning,20,1,Medium >15min,...,175,Short Haul >1500Mi,0,0,0,0,0,AIRBUS,A320,17
6743399,2023-12-31,7,JetBlue Airways,N903JB,SJU,"San Juan, PR",Morning,4,1,Low <5min,...,219,Medium Haul <3000Mi,0,0,0,0,0,AIRBUS,A321,11
6743400,2023-12-31,7,JetBlue Airways,N535JB,MCO,"Orlando, FL",Evening,113,1,Hight >60min,...,162,Short Haul >1500Mi,4,0,0,0,96,AIRBUS,A320,22
6743401,2023-12-31,7,JetBlue Airways,N354JB,PHL,"Philadelphia, PA",Afternoon,-11,0,Low <5min,...,73,Short Haul >1500Mi,0,0,0,0,0,EMBRAER,190/195,11
6743402,2023-12-31,7,JetBlue Airways,N768JB,PBI,"West Palm Beach/Palm Beach, FL",Afternoon,-7,0,Low <5min,...,158,Short Haul >1500Mi,0,0,0,0,0,AIRBUS,A320,15
6743403,2023-12-31,7,JetBlue Airways,N547JB,BDL,"Hartford, CT",Morning,-8,0,Low <5min,...,173,Short Haul >1500Mi,0,0,0,0,0,AIRBUS,A320,22

In [ ]:
num_cols = ["Dep_Delay", "Arr_Delay", "Flight_Duration", "Aicraft_age",
            "Delay_Carrier", "Delay_Weather", "Delay_NAS"]

data.[num_cols].hist(bins=50, figsize=(14, 8))
plt.tight_layout()
plt.show()